export default [
    ["letter", "a"],
    ["letter", "b"],
    ["letter", "c"],
    ["letter", "d"],
    ["letter", "e"],
    ["letter", "g"],
    ["letter", "h"],
    ["letter", "i"],
    ["letter", "j"],
    ["letter", "k"],
    ["letter", "l"],
    ["letter", "m"],
    ["letter", "n"],
    ["letter", "o"],
    ["letter", "p"],
    ["letter", "q"],
    ["letter", "r"],
    ["letter", "s"],
    ["letter", "t"],
    ["letter", "u"],
    ["letter", "v"],
    ["letter", "w"],
    ["letter", "x"],
    ["letter", "y"],
    ["letter", "z"],
    ["music", "tone"],
    ["music", "guitar"],
    ["music","piano"],
    ["award","medal"],
    ["award","trophy"],
    ["fruit","banana"],
    ["insect","caterpillar"],
    ["animal","squirrel"],
    ["hand","ok"],
    ["hand","thumbsup"],
    ["hand","thumbsdown"],
    ["ghost","scary"],
    ["head","alien"],
    ["mouth","hickey"],
    ["ring","diamond"],
    ["sign","adult"],
    ["number","10"],
    ["knife","sharp"],
    ["vehicle","bus"],
    ["vehicle","truck"],
    ["finger","crossed"],
    ["face","angry"],
    ["face","vomit"],
    ["dress","karate"],
    ["egg","round"],
    ["animal","fox"],
    ["lizard","crawling"],
    ["bird","parrot"],
    ["word","free"],
    ["chilli","spicy"],
    ["watermelon","slice"],
    ["fruit","cherries"],
    ["fruit","strawberry"],
    ["burger","cheesy"],
    ["icecream","yummy"],
    ["cake","slice"],
    ["animal","pig"],
    ["animal","elephant"],
    ["octopus","tentacles"],
    ["fish","fish"],
    ["tortoise","slow"],
    ["bird","chick"],
    ["whale","big"],
    ["eye","staring"],
    ["hand","up"],
    ["hand","down"],
    ["hand","left"],
    ["hand","right"],
    ["skull","dead"],
    ["key","open"],
    ["bell","ring"],
    ["fire","burning"],
    ["hammer","tool"],
    ["hand","five"],
    ["finger","middle"],
    ["rocket","flying"],
    ["hand","rock"],
    ["face","freezing"],
    ["unicorn","fantasy"],
    ["animal","bat"],
    ["squid","small"],
    ["underwear","comfy"],
    ["bandage","injury"],
    ["hug","friends"],
    ["head","crown"],
    ["hand","love"],
    ["number","zero"],
    ["number","one"],
    ["number","two"],
    ["number","three"],
    ["number","four"],
    ["number","five"],
    ["number","six"],
    ["number","seven"],
    ["number","eight"],
    ["number","nine"],
    ["time","sands"],
    ["finger","one"],
    ["palm","stop"],
    ["hand","peas"],
    ["pencil","write"],
    ["sign","danger"],
    ["sun","shiny"],
    ["umberalla","rainy"],
    ["tea","hot"],
    ["symbol","pirate"],
    ["symbol","heart"],
    ["symbol","diamond"],
    ["swords","battle"],
    ["aeroplane","flying"],
    ["mail","envelope"],
    ["pen","write"],
    ["symbol","freeze"],
    ["sign","upward"],
    ["sign","downward"],
  
]